name: "Commit Changes"
description: "Commits and pushes changes to the repository"

inputs:
  commit-message:
    description: "Commit message"
    required: true
  file-path:
    description: "Path to file to commit"
    required: false
    default: "README.md"

runs:
  using: "composite"
  steps:
    - name: Check for changes
      id: check_changes
      shell: bash
      run: |
        git diff --quiet ${{ inputs.file-path }} || echo "::set-output name=has_changes::true"

    - name: Commit and push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ inputs.file-path }}
        git commit -m "${{ inputs.commit-message }}"
        git push
