name: Update GitHub Stats

on:
  schedule:
    - cron: "45 0 * * *" # Runs at 00:45 every day
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate GitHub Stats
        id: stats
        uses: anmol098/waka-readme-stats@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN || github.token }}
          USERNAME: ${{ github.repository_owner }}
        with:
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LOC_CHART: "False"
          SECTION_NAME: "stats"
          COMMIT_MESSAGE: "Updated GitHub stats"

      - name: Replace stats section in README if waka-readme-stats fails
        if: ${{ failure() && steps.stats.conclusion == 'failure' }}
        uses: ./.github/actions/section-replacer
        with:
          section-name: "stats"
          section-content: |
            ## 📊 GitHub Stats

            <div align="center" class="stats-container">
              <img src="https://streak-stats.demolab.com/?user=Raghav-56&theme=github-dark-blue" alt="Raghav's GitHub streak" class="responsive-img"/>
              <img src="https://github-readme-stats.vercel.app/api?username=Raghav-56&show_icons=true&theme=radical" alt="Raghav's GitHub stats" class="responsive-img"/>
            </div>

      - name: Commit changes if waka-readme-stats fails
        if: ${{ failure() && steps.stats.conclusion == 'failure' }}
        uses: ./.github/actions/commit-changes
        with:
          commit-message: "Updated GitHub stats (manual fallback)"
