name: Reusable Commit Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
        description: "Commit message"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Commit Changes
        uses: ./.github/actions/commit-changes
        with:
          commit-message: ${{ inputs.message }}
